[[sysimage]]
arch = "x86_64"
git-tree-sha1 = "c02071490a44ac896da1c92ad7045450af9e588a"
os = "linux"

    [[sysimage.download]]
    sha256 = "ac82d728c0d46fdcd81e47872770d3585d5a57bb6dc09cae6193f5af02cface4"
    url = "https://github.com/jbrea/MLCourse/releases/download/sysimages/ubuntu-latest-x64-1.7.tar.gz"

[[sysimage]]
arch = "x86_64"
git-tree-sha1 = "664fc6f0a66cce2a88ba70021aa661be0fee1d3f"
os = "macos"

    [[sysimage.download]]
    sha256 = "bf133bcfeec60246b5b1619ad7fa41c3196f50c4390851d41cb8c5be88028a5b"
    url = "https://github.com/jbrea/MLCourse/releases/download/sysimages/macOS-latest-x64-1.7.tar.gz"

[[sysimage]]
arch = "x86_64"
git-tree-sha1 = "76dac446e48683e74b0ab4a2bee499a25b1a2db9"
os = "windows"

    [[sysimage.download]]
    sha256 = "1ed6d3bc6a4389e08a10b920a60b2763638e079e958901e45b5c369218453f15"
    url = "https://github.com/jbrea/MLCourse/releases/download/sysimages/windows-latest-x64-1.7.tar.gz"

