[[sysimage]]
arch = "x86_64"
git-tree-sha1 = "99e515f8f1b2d4b9f5ae03bf3f569a2e9c22b1fd"
os = "linux"

    [[sysimage.download]]
    sha256 = "835dc59d89be4d415baf28730d670fc395bc06d05334c4158c303511b2838070"
    url = "https://github.com/jbrea/MLCourse/releases/download/sysimages/ubuntu-latest-x64-1.7.tar.gz"

[[sysimage]]
arch = "x86_64"
git-tree-sha1 = "42f114bff7bbeb6f64ac78d9cb78580223bb3a47"
os = "macos"

    [[sysimage.download]]
    sha256 = "75beafb64b167505bb66ea8ef14c7140b8efc66ae90fe46fbe1642c9a74efc00"
    url = "https://github.com/jbrea/MLCourse/releases/download/sysimages/macOS-latest-x64-1.7.tar.gz"

[[sysimage]]
arch = "x86_64"
git-tree-sha1 = "76dac446e48683e74b0ab4a2bee499a25b1a2db9"
os = "windows"

    [[sysimage.download]]
    sha256 = "1ed6d3bc6a4389e08a10b920a60b2763638e079e958901e45b5c369218453f15"
    url = "https://github.com/jbrea/MLCourse/releases/download/sysimages/windows-latest-x64-1.7.tar.gz"

